# Generated by Django 3.2.8 on 2021-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terego', '0002_auto_20211201_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
